name: Docker Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build -t renderman .
    - run: docker run -v $(pwd)/vol:/vol renderman python3.11 -m renderman.docker_test
